source 'https://github.com/CocoaPods/cocoapods-test-specs.git'
project 'SampleApp.xcodeproj'
platform :ios, '9.3'

target 'SampleApp' do
    pod 'ReactiveSwift', git: 'https://github.com/ReactiveCocoa/ReactiveSwift.git', :tag => '6.0.0'

    pod 'Workflow', path: '../../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../../WorkflowUI.podspec', :testspecs => ['Tests']
end

target 'SampleAppTests' do
    pod 'Workflow', path: '../../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../../WorkflowUI.podspec', :testspecs => ['Tests']
    pod 'WorkflowTesting', path: '../../../WorkflowTesting.podspec', :testspecs => ['Tests']
end
